### ISSUE TITLE
flash export swf error 

### ISSUE THREAD

**Issue by xinhua0228** [BlackMATov/unity-flash-tools#3]
[Start]
[Document] '1400479.fla' conversion started...
The following JavaScript error(s) occurred:

At line 889 of file "FTMain.jsfl":
The function unlockAllElements() is currently unavailable.

**Comment by BlackMATov** [comment]
Hello!

Can you provide me your Adobe Flash/Animate version and ".fla" source?
Without that information, I have no chance to understand what's wrong there.

P.S.
You can send the .fla file to my email to prevent showing it in public.

**Comment by xinhua0228** [comment]
Email has been sent。
