### ISSUE TITLE
Errors while exporting

### ISSUE THREAD

**Issue by XMOAO** [BlackMATov/unity-flash-tools#6]
While exporting the assets,it occurs some errors:

Assets\FlashTools\Scripts\Editor\FTEditor\SwfEditorUtils.cs(235,54): error CS0433: The type 'CompressionMode' exists in both 'Ionic.Zip.Unity and 'Unity.VisualScripting.IonicZip

Assets\FlashTools\Scripts\Editor\FTSwfTools\SwfStreamReader.cs(199,25): error CS0433: The type 'ZlibStream' exists in both 'Ionic.Zip.Unity and 'Unity.VisualScripting.IonicZip

I do not know how to fix...

**Comment by BlackMATov** [comment]
Hello! Yeah, just remove Assets/FlashTools/Plugins/Editor/Ionic.Zip.Unity.dll.

It happens because modern Unity versions use and include some zip library that I use and include too (as far as I remember in the visual scripting package).

**Comment by XMOAO** [comment]
thanks for answering.Now i have another question.

I want to know whether it can control the layers?
Because in .fla some layers may not be displayed in certain circumstances.I want to control which layer should be displayed.
Does it support?

**Comment by BlackMATov** [comment]
No, you can’t control a visibility of layers, because it no exist in compiled swf. Also, you can’t control separated parts of an animation, because all this parts are baked to a frame geometry.

**Comment by XMOAO** [comment]
OK,I see.So the proper alternative is to separate the whole .fla into several complied .swf and use them independently?

**Comment by BlackMATov** [comment]
Оr separated movie clips in one swf and play them as two swfclip.

**Comment by XMOAO** [comment]
Ok,i see.Thanks for replying.It is powerful enough for me! Such a good tool.
